package ApplicationManager.Authentication;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

import com.formdev.flatlaf.FlatLightLaf;

import java.awt.image.BufferedImage;
import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import javax.swing.*;

/**
 *
 * @author vlad
 */
public class Users_Profile extends javax.swing.JPanel {

    /**
     * Creates new form Users_Roles
     */
    
    private BufferedImage originalImage;
    private JFileChooser fileChooser;
    
    public Users_Profile()
    {     
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Users_Profile.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        edit_name = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        number_phone = new javax.swing.JFormattedTextField();
        name = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        country_select = new javax.swing.JComboBox<>();
        edit_number_phone = new javax.swing.JButton();
        edit_image = new javax.swing.JButton();
        edit_description = new javax.swing.JButton();

        image.setBackground(new java.awt.Color(229, 236, 234));
        image.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        image.setEnabled(false);

        edit_name.setText("Edit");
        edit_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_nameActionPerformed(evt);
            }
        });

        description.setBackground(new java.awt.Color(229, 236, 234));
        description.setColumns(20);
        description.setRows(5);
        description.setEnabled(false);
        jScrollPane1.setViewportView(description);

        jLabel3.setText("Full name:");

        jLabel5.setText("Number Phone:");

        number_phone.setBackground(new java.awt.Color(229, 236, 234));
        number_phone.setEnabled(false);

        name.setBackground(new java.awt.Color(229, 236, 234));
        name.setEnabled(false);

        jLabel6.setText("Country:");

        country_select.setBackground(new java.awt.Color(229, 236, 234));
        country_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "........", "Romania", "Germany", "France", "Italy", "Spain", "United Kingdom", "Poland", "Greece", "Sweden", "Norway", "United States", "Canada", "Mexico", "South Korea", "New Zealand", "Australia", "Indonesia", "Thailand", "Vietnam", "Malaysia", "Philippines", "Saudi Arabia", "China", "Japan", "India", "Nigeria", "Egypt", "South Africa", "Kenya", "Morocco", "Algeria", "Ghana", "Ethiopia", "Tanzania", "Senegal", "Cuba", "Dominican Republic", "Guatemala", "Honduras", "Costa Rica", "Panama", "Jamaica", "Brazil", "Argentina", "Chile", "Peru", "Colombia", "Venezuela", "Ecuador", "Bolivia", "Paraguay", "Uruguay", "Fiji", "Papua New Guinea", "Samoa", "Tonga", "Vanuatu", "Solomon Islands", "Kiribati", "Tuvalu" }));
        country_select.setEnabled(false);

        edit_number_phone.setText("Edit");
        edit_number_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_number_phoneActionPerformed(evt);
            }
        });

        edit_image.setText("Edit");
        edit_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_imageActionPerformed(evt);
            }
        });

        edit_description.setText("Edit Description");
        edit_description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_descriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edit_description)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(number_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(edit_number_phone))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(221, 221, 221))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edit_name, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(country_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edit_image, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(317, 317, 317))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit_image, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(country_select, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit_number_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(edit_description, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void edit_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_nameActionPerformed
       name.setEnabled(true);
       country_select.setEnabled(true);
    }//GEN-LAST:event_edit_nameActionPerformed

    private void edit_number_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_number_phoneActionPerformed
        number_phone.setEnabled(true);
    }//GEN-LAST:event_edit_number_phoneActionPerformed

    private void edit_descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_descriptionActionPerformed
        description.setEnabled(true);
    }//GEN-LAST:event_edit_descriptionActionPerformed

    private void edit_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_imageActionPerformed
        image.setEnabled(true);
        fileChooser = new JFileChooser();        
        setScaledImage(image);
    }//GEN-LAST:event_edit_imageActionPerformed

    public String setScaledImage(JLabel label) 
    {
        int result = fileChooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            
            String base_dir = Paths.get("").toAbsolutePath().toString() + "/src/main/";
            
            Path absolutePathObj = Paths.get(selectedFile.getAbsolutePath());
            Path baseDirPath = Paths.get(base_dir);
            Path relativePath = baseDirPath.relativize(absolutePathObj);
            
            try {
                originalImage = ImageIO.read(selectedFile);
                
                int Width = label.getWidth();
                int Height = label.getHeight();

                BufferedImage resizedImage = new BufferedImage(Width, Height, BufferedImage.TYPE_INT_ARGB);
                Graphics2D g2d = resizedImage.createGraphics();

                g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
                g2d.drawImage(originalImage, 0, 0, Width, Height, null);
                g2d.dispose();

                label.setIcon(new ImageIcon(resizedImage));
                label.setText(null);
                
            } catch (Exception ex) { JOptionPane.showMessageDialog(this, ""); }
            
            return "/" + relativePath.toString().replace("\\", "/");
        }
        
        return "";
    }  
    
    public String getPathImage() { return setScaledImage(image); }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> country_select;
    public javax.swing.JTextArea description;
    private javax.swing.JButton edit_description;
    private javax.swing.JButton edit_image;
    private javax.swing.JButton edit_name;
    private javax.swing.JButton edit_number_phone;
    public javax.swing.JLabel image;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JFormattedTextField name;
    public javax.swing.JFormattedTextField number_phone;
    // End of variables declaration//GEN-END:variables
}
