package org.accessshield_backup;

import core.AccountSession;
import Entities.*;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.text.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.*;
import jpa.*;

/**
 *
 * @author vlad
 */
public class CreateReservation extends javax.swing.JFrame {
    private BigDecimal pricePerRoom;
    public int stage = 0;
    
    /**
     * Creates new form CreateReservation
     */
    
    public CreateReservation() {
        initComponents();
        
        setLocationRelativeTo(null);
        fillRooms();
        UpdateNextDateFromSpinner();
    }
    
    private void fillRooms() {
        new Thread(() -> {
            String buildingName = AccountSession.getBuildingName();
            BuildingJpaController bjc = new BuildingJpaController();
            RoomsJpaController rjc = new RoomsJpaController();
            
            Building building = bjc.getBuildingByName(buildingName);
            pricePerRoom = building.getPrice();
            List<Integer> rooms = rjc.GetAllAvailableRooms(building.getId());
            
            for(int i = 0; i < rooms.size(); i++)
                this.rooms.addItem(rooms.get(i) + "");
            
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rooms = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nextTime = new javax.swing.JLabel();
        days = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Reservation");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Number of days:");

        rooms.setName("rooms"); // NOI18N

        jLabel2.setText("Available rooms:");

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Book Now");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        nextTime.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        nextTime.setText("22-01-2025");
        nextTime.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        days.setModel(new javax.swing.SpinnerNumberModel(1, 1, 366, 1));
        days.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                daysStateChanged(evt);
            }
        });

        jLabel3.setText("Due to date:");

        jLabel4.setText("Total Price:");

        totalPrice.setText("0 $");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jButton2)
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel3)))
                        .addGap(52, 52, 52))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel4)
                        .addGap(73, 73, 73)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rooms, 0, 139, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(nextTime, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(days)))
                .addGap(128, 128, 128))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextTime)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(totalPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        BuildingJpaController bjc = new BuildingJpaController();
        AccountJpaController ajc = new AccountJpaController();
        
        BookingJpaController boojc = new BookingJpaController();
        RoomsJpaController rjc = new RoomsJpaController();
        
        Account account = ajc.getAccountFromUsername(AccountSession.getUsername());
        LocalDateTime now = LocalDateTime.now();
        Timestamp checkIn = Timestamp.valueOf(now);
        
        int totalDays = Integer.parseInt(days.getValue().toString());
        Timestamp checkOut = Timestamp.valueOf(now.plusDays(totalDays));
        
        Booking book = new Booking();
        book.setAccountId(account);
        book.setCheckIn(checkIn);
        
        book.setCheckOut(checkOut);
        book.setStatus("pending");
        
        int roomId = Integer.parseInt(rooms.getItemAt(rooms.getSelectedIndex()));
        Rooms room = rjc.GetRoomById(roomId);
        
        rjc.UpdateRoomStatus(room.getRoomId(), "occupied");
        book.setRoomId(room);
        
        boojc.CreateBooking(book);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int returnCode = JOptionPane.showConfirmDialog(this,
        "Would you like to cancel this reservation?",
        "New Reservation",
        JOptionPane.WARNING_MESSAGE);
        
        /* inchide fereastra principala daca utilizatorul confirma in fereastra de dialog */
        if(returnCode == JOptionPane.OK_OPTION) this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int returnCode = JOptionPane.showConfirmDialog(this, "Would you like to cancel this reservation?",
        "New Reservation", JOptionPane.WARNING_MESSAGE);
        
        /* inchide fereastra principala daca utilizatorul confirma in fereastra de dialog */
        if(returnCode == JOptionPane.OK_OPTION) this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void daysStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_daysStateChanged
        UpdateNextDateFromSpinner();
    }//GEN-LAST:event_daysStateChanged

    private void UpdateNextDateFromSpinner() {
        LocalDateTime now = LocalDateTime.now();
        int totalDays = Integer.parseInt(days.getValue().toString());
        LocalDateTime afterDate = now.plusDays(totalDays);
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String formattedDate = afterDate.format(formatter);
        nextTime.setText(formattedDate);
        
        DecimalFormat df = new DecimalFormat("#.00");
        BigDecimal totalPrice = pricePerRoom.multiply(BigDecimal.valueOf(totalDays));
        this.totalPrice.setText(df.format(totalPrice) + " $");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CreateReservation().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner days;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nextTime;
    private javax.swing.JComboBox<String> rooms;
    private javax.swing.JLabel totalPrice;
    // End of variables declaration//GEN-END:variables
}
