package org.accessshield_backup;

import Entities.Account;
import Entities.UsersRoles;
import core.ManagerEntities;
import jpa.AccountJpaController;

/**
 *
 * @author vlad
 */
public class Setup_Role extends javax.swing.JFrame 
{   
    private AccountJpaController ajc;
    private Account account;
    private ManagerEntities em;  
    private SignUp signup;
    
    /**
     * Creates new form Setup_Role
     */
    public Setup_Role() 
    {
        initComponents();
        
        ajc = new AccountJpaController();    
        em = new ManagerEntities();      
        signup = new SignUp();
        
        initWindow();
    }
    
    private void initWindow() 
    {   
        if (signup.Index > 0) 
        {
            account = em.getManagerEntities().find(Account.class, signup.Index);

            String userRole = ajc.GetUserRole();
            int selectedIndex = userRole.isEmpty() ? -1 : (userRole.equals("admin") ? 0 : 1);

            if(selectedIndex >= 0) setup_User_Role2.select.setSelectedIndex(selectedIndex);
            setup_User_Role2.username.setText(account.getUsername());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        save_changes = new javax.swing.JButton();
        next_page = new javax.swing.JButton();
        setup_User_Role2 = new ApplicationManager.UI_UserManagement.Setup_User_Role();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Set User Role");

        save_changes.setText("Apply");
        save_changes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_changesActionPerformed(evt);
            }
        });

        next_page.setText("Next");
        next_page.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        next_page.setEnabled(false);
        next_page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_pageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(next_page, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(save_changes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(setup_User_Role2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(setup_User_Role2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(next_page, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(save_changes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void save_changesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_changesActionPerformed
        UsersRoles role = new UsersRoles();
        role.setAccountId(ajc.getAccountFromUsername(new SignUp().register2.username.getText()));
        
        if (setup_User_Role2.select.getSelectedItem().equals(".................................")) { //jcombobox
            setup_User_Role2.select.setSelectedIndex(setup_User_Role2.select.getSelectedIndex());
            setup_User_Role2.select.setSelectedItem("quest");
            
            role.setRole("quest");
            ajc.InsertUserRole(role);
        }
        if (setup_User_Role2.select.getSelectedItem().equals("admin") || setup_User_Role2.select.getSelectedItem().equals("quest")) 
        {
            role.setRole(setup_User_Role2.select.getSelectedItem().toString());   
            String userRole = setup_User_Role2.select.getSelectedItem().toString();
            
            ajc.InsertUserRole(role);
        }
        next_page.setEnabled(true);
    }//GEN-LAST:event_save_changesActionPerformed

    private void next_pageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_pageActionPerformed
        new UsersProfile().setVisible(true);
        dispose();
    }//GEN-LAST:event_next_pageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setup_Role.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Setup_Role().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton next_page;
    private javax.swing.JButton save_changes;
    private ApplicationManager.UI_UserManagement.Setup_User_Role setup_User_Role2;
    // End of variables declaration//GEN-END:variables
}
